port: 8081
addressing: localhost:8081
serverAddressing: localhost:8091
tm:
  commitRetryCount: 5
  rollbackRetryCount: 5
at:
  dsn: "root:123456@tcp(127.0.0.1:3306)/seata_product?timeout=5s&readTimeout=5s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
  report_retry_count: 5
  report_success_enable: false
  lock_retry_interval: 10ms
  lock_retry_times: 30
enforcementPolicy:
  minTime: 5s
  permitWithoutStream: true
serverParameters:
  maxConnectionIdle: 15s
  maxConnectionAge: 30s
  maxConnectionAgeGrace: 5s
  time: 5s
  timeout: 1s
clientParameters:
  time: 10s
  timeout: 1s
  permitWithoutStream: true
